version: "3.8"
services:
  database:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./prisma:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"
