# name: Docker Image CI

# on:
#     push:
#         branches:
#             - master

# jobs:
#     build:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Checkout
#               uses: actions/checkout@v3
#             - name: Login to Docker Hub
#               uses: docker/login-action@v2
#               with:
#                   username: ${{ secrets.DOCKERHUB_USERNAME }}
#                   password: ${{ secrets.DOCKERHUB_TOKEN }}
#             - name: Set up Docker Buildx
#               uses: docker/setup-buildx-action@v2
#             - name: Build and push
#               uses: docker/build-push-action@v4
#               with:
#                   context: .
#                   build-args: |
#                       NODE_OPTIONS="--max_old_space_size=8192"
#                       NEXT_PUBLIC_APP_FRONTEND_BASE_URL=${{ secrets.NEXT_PUBLIC_APP_FRONTEND_BASE_URL }}
#                       NEXT_PUBLIC_APP_BACKEND_BASE_URL=${{ secrets.NEXT_PUBLIC_APP_BACKEND_BASE_URL }}
#                       NEXT_PUBLIC_APP_WEBSITE_BASE_URL=${{ secrets.NEXT_PUBLIC_APP_WEBSITE_BASE_URL }}
#                       NEXT_PUBLIC_ATHENA_BACKEND_BASE_URL=${{ secrets.NEXT_PUBLIC_ATHENA_BACKEND_BASE_URL }}
#                       POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
#                       POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
#                       POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}
#                       POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
#                       POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }}
#                       MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}
#                       MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}
#                       GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
#                       GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
#                       GOOGLE_REFRESH_TOKEN=${{ secrets.GOOGLE_REFRESH_TOKEN }}
#                       GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}
#                       GOOGLE_EMAIL=${{ secrets.GOOGLE_EMAIL }}
#                       NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID }}
#                       NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_SECRET }}
#                       NEXT_PUBLIC_GOOGLE_OAUTH_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_GOOGLE_OAUTH_REDIRECT_URI }}
#                       AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
#                       AWS_REGION=${{ secrets.AWS_REGION }}
#                       AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
#                       AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
#                       LAMBDA_URL_GITHUB_STATS=${{ secrets.LAMBDA_URL_GITHUB_STATS }}
#                       LAMBDA_URL_LINKEDIN_STATS=${{ secrets.LAMBDA_URL_LINKEDIN_STATS }}
#                       LAMBDA_URL_LEETCODE_STATS=${{ secrets.LAMBDA_URL_LEETCODE_STATS }}
#                       LAMBDA_URL_MEDIUM_STATS=${{ secrets.LAMBDA_URL_MEDIUM_STATS }}
#                       LAMBDA_URL_KAGGLE_STATS=${{ secrets.LAMBDA_URL_KAGGLE_STATS }}
#                       LAMBDA_URL_CODEFORCES_STATS=${{ secrets.LAMBDA_URL_CODEFORCES_STATS }}
#                       LAMBDA_URL_CODECHEF_STATS=${{ secrets.LAMBDA_URL_CODECHEF_STATS }}
#                       LAMBDA_URL_BEHANCE_STATS=${{ secrets.LAMBDA_URL_BEHANCE_STATS }}
#                       LAMBDA_URL_DRIBBBLE_STATS=${{ secrets.LAMBDA_URL_DRIBBBLE_STATS }}
#                       LAMBDA_URL_GFG_STATS=${{ secrets.LAMBDA_URL_GFG_STATS }}
#                       LAMBDA_URL_HASHNODE_STATS=${{ secrets.LAMBDA_URL_HASHNODE_STATS }}
#                       LAMBDA_URL_STACKOVERFLOW_STATS=${{ secrets.LAMBDA_URL_STACKOVERFLOW_STATS }}
#                       JWT_SECRET=${{ secrets.JWT_SECRET }}
#                       NEXT_PUBLIC_GA_TRACKING_ID=${{ secrets.NEXT_PUBLIC_GA_TRACKING_ID }}
#                       NEXT_PUBLIC_DUMMY_USER_EMAIL=${{ secrets.NEXT_PUBLIC_DUMMY_USER_EMAIL }}
#                   file: ./Dockerfile
#                   push: true
#                   tags: ${{ secrets.DOCKERHUB_USERNAME }}/opengig-product:latest
